#!/bin/bash
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#

#
# Copyright (c) 2015, Joyent, Inc.
#

#
# Rsync the master in this working copy to the install on the given HN.
#

#set -o xtrace
set -o errexit

TOP=$(cd $(dirname $0)/../; pwd)
NODE=$1

DEST=/opt/smartdc/agents/lib/node_modules/cn-agent/node_modules/sdc-docker-build

rsync -av ${TOP}/ \
    $NODE:$DEST/ \
    $extraOpts \
    --exclude '.git*' \
    --exclude /deps/ \
    --exclude /doc/ \
    --exclude /tmp/ \
    --exclude /tools/
